### ISSUE TITLE
DB neu anlegen, purge db script

### ISSUE THREAD

**Issue by wielanms** [steimlfk/echo-api#15]
- Accounts hinzufügen
Darauf achten, dass die DB User und die Accounts gelöscht werden bei purge.
Bei den Anlegen der Accounts müssen auch User angelegt werden und Rechte vergeben werden.
Es geht nur um die Beispieluser patient1, dr.who

- Fragen anlegen

**Comment by steimlfk** [comment]
update script recreates the following accounts:

doc: dr.who
patients: averel and joe

and several medial values and questions
