### ISSUE TITLE
Reminder Analyzer II

### ISSUE THREAD

**Issue by steimlfk** [steimlfk/echo-api#29]
Some patients may forget to fill in their report for days. Remind them!

Write a function which is called on a regular basis, which checks if the patient hasnt filled in his daily report for N days and remind him to do so!

**Comment by hueneburg** [comment]
n is set to 5. done

**Comment by steimlfk** [comment]
It isn't sufficient just to alter the sql statement.

The generated notification is still "You are dead."
The notification doenst get stored in the db.
The code which should send the notification just sends one object to every niotification-api. This causes unnecessary errors.

Please dont hard-code the n=5 in the sql statement. Create a function parameter (see newDailyReport).
