### ISSUE TITLE
Check Token expiration

### ISSUE THREAD

**Issue by wielanms** [steimlfk/echo-api#4]
4) Session tokens acquired with the login process seem to be functional for hours after their expiration. For example using token:
`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50SWQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTQxNTI2OTQxMiwiZXhwIjoxNDE1ODc0MjEyfQ.Ex3p-ucXOz3hXpqYr2kq8oHtcsTejHwxJsP9zQewMFM`
 that should have expired at Thu, 06 Nov 2014 13:28:45 GMT, I could still make requests for the next couple of days.

**Comment by steimlfk** [comment]
Token Expiration date was 13.11.2014, so this seems to work properly
