### ISSUE TITLE
Create the questions

### ISSUE THREAD

**Issue by wielanms** [steimlfk/echo-api#7]
Q1: Did your shortness of breath increase?

Q1a: Can you do the daily work you did before? 
Q1b: Can you support yourself (go to toilet, shower)? 
Q1c:Can you walk?

Q2: Did your cough increase?

Q3: Did your sputum change?
Q3a: Is your sputum yellow? 
Q3b: Is it green? 
Q3c: Or bloody?
Q4: Did you have chest pain or discomfort?
Q5: Did you take the same medications? Or increased them?

**Comment by steimlfk** [comment]
created and added to create.sql
